################################################################################
# Automatically-generated file. Do not edit!
# Toolchain: GNU Tools for STM32 (9-2020-q2-update)
################################################################################

# Add inputs and outputs from these tool invocations to the build variables 
C_SRCS += \
F:/DS_STM32F429/IAP/CycloneBOOT_IAP_Demo_Open_1_0_1/cyclone_boot/iap/crc32.c \
F:/DS_STM32F429/IAP/CycloneBOOT_IAP_Demo_Open_1_0_1/cyclone_boot/iap/iap_app.c \
F:/DS_STM32F429/IAP/CycloneBOOT_IAP_Demo_Open_1_0_1/cyclone_boot/iap/iap_auth.c \
F:/DS_STM32F429/IAP/CycloneBOOT_IAP_Demo_Open_1_0_1/cyclone_boot/iap/iap_check.c \
F:/DS_STM32F429/IAP/CycloneBOOT_IAP_Demo_Open_1_0_1/cyclone_boot/iap/iap_cipher.c \
F:/DS_STM32F429/IAP/CycloneBOOT_IAP_Demo_Open_1_0_1/cyclone_boot/iap/iap_sign.c \
F:/DS_STM32F429/IAP/CycloneBOOT_IAP_Demo_Open_1_0_1/cyclone_boot/iap/drivers/stm32f4xx_flash_driver.c 

OBJS += \
./CycloneBOOT_Sources/crc32.o \
./CycloneBOOT_Sources/iap_app.o \
./CycloneBOOT_Sources/iap_auth.o \
./CycloneBOOT_Sources/iap_check.o \
./CycloneBOOT_Sources/iap_cipher.o \
./CycloneBOOT_Sources/iap_sign.o \
./CycloneBOOT_Sources/stm32f4xx_flash_driver.o 

C_DEPS += \
./CycloneBOOT_Sources/crc32.d \
./CycloneBOOT_Sources/iap_app.d \
./CycloneBOOT_Sources/iap_auth.d \
./CycloneBOOT_Sources/iap_check.d \
./CycloneBOOT_Sources/iap_cipher.d \
./CycloneBOOT_Sources/iap_sign.d \
./CycloneBOOT_Sources/stm32f4xx_flash_driver.d 


# Each subdirectory must supply rules for building sources it contributes
CycloneBOOT_Sources/crc32.o: F:/DS_STM32F429/IAP/CycloneBOOT_IAP_Demo_Open_1_0_1/cyclone_boot/iap/crc32.c CycloneBOOT_Sources/subdir.mk
	arm-none-eabi-gcc "$<" -mcpu=cortex-m4 -std=gnu11 -g3 -DSTM32F429xx -DUSE_HAL_DRIVER -DUSE_STM32F4XX_NUCLEO_144 -DIAP_SCENARIO_1 -D_WINSOCK_H -c -I"F:/DS_STM32F429/IAP/CycloneBOOT_IAP_Demo_Open_1_0_1/demo/st/nucleo_f429zi/http_server_iap_demo/stm32_cube_ide/../src" -I"F:/DS_STM32F429/IAP/CycloneBOOT_IAP_Demo_Open_1_0_1/demo/st/nucleo_f429zi/http_server_iap_demo/stm32_cube_ide/../../../../../third_party/cmsis/include" -I"F:/DS_STM32F429/IAP/CycloneBOOT_IAP_Demo_Open_1_0_1/demo/st/nucleo_f429zi/http_server_iap_demo/stm32_cube_ide/../../../../../third_party/st/devices/stm32f4xx" -I"F:/DS_STM32F429/IAP/CycloneBOOT_IAP_Demo_Open_1_0_1/demo/st/nucleo_f429zi/http_server_iap_demo/stm32_cube_ide/../../../../../third_party/st/drivers/stm32f4xx_hal_driver/inc" -I"F:/DS_STM32F429/IAP/CycloneBOOT_IAP_Demo_Open_1_0_1/demo/st/nucleo_f429zi/http_server_iap_demo/stm32_cube_ide/../../../../../third_party/st/boards/stm32f4xx_nucleo_144" -I"F:/DS_STM32F429/IAP/CycloneBOOT_IAP_Demo_Open_1_0_1/demo/st/nucleo_f429zi/http_server_iap_demo/stm32_cube_ide/../../../../../third_party/freertos/include" -I"F:/DS_STM32F429/IAP/CycloneBOOT_IAP_Demo_Open_1_0_1/demo/st/nucleo_f429zi/http_server_iap_demo/stm32_cube_ide/../../../../../third_party/freertos/portable/gcc/arm_cm4f" -I"F:/DS_STM32F429/IAP/CycloneBOOT_IAP_Demo_Open_1_0_1/demo/st/nucleo_f429zi/http_server_iap_demo/stm32_cube_ide/../../../../../common" -I"F:/DS_STM32F429/IAP/CycloneBOOT_IAP_Demo_Open_1_0_1/demo/st/nucleo_f429zi/http_server_iap_demo/stm32_cube_ide/../../../../../cyclone_tcp" -I"F:/DS_STM32F429/IAP/CycloneBOOT_IAP_Demo_Open_1_0_1/demo/st/nucleo_f429zi/http_server_iap_demo/stm32_cube_ide/../../../../../cyclone_ssl" -I"F:/DS_STM32F429/IAP/CycloneBOOT_IAP_Demo_Open_1_0_1/demo/st/nucleo_f429zi/http_server_iap_demo/stm32_cube_ide/../../../../../cyclone_crypto" -I"F:/DS_STM32F429/IAP/CycloneBOOT_IAP_Demo_Open_1_0_1/demo/st/nucleo_f429zi/http_server_iap_demo/stm32_cube_ide/../../../../../cyclone_boot" -O0 -ffunction-sections -Wall -fstack-usage -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@"  -mfpu=fpv4-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
CycloneBOOT_Sources/iap_app.o: F:/DS_STM32F429/IAP/CycloneBOOT_IAP_Demo_Open_1_0_1/cyclone_boot/iap/iap_app.c CycloneBOOT_Sources/subdir.mk
	arm-none-eabi-gcc "$<" -mcpu=cortex-m4 -std=gnu11 -g3 -DSTM32F429xx -DUSE_HAL_DRIVER -DUSE_STM32F4XX_NUCLEO_144 -DIAP_SCENARIO_1 -D_WINSOCK_H -c -I"F:/DS_STM32F429/IAP/CycloneBOOT_IAP_Demo_Open_1_0_1/demo/st/nucleo_f429zi/http_server_iap_demo/stm32_cube_ide/../src" -I"F:/DS_STM32F429/IAP/CycloneBOOT_IAP_Demo_Open_1_0_1/demo/st/nucleo_f429zi/http_server_iap_demo/stm32_cube_ide/../../../../../third_party/cmsis/include" -I"F:/DS_STM32F429/IAP/CycloneBOOT_IAP_Demo_Open_1_0_1/demo/st/nucleo_f429zi/http_server_iap_demo/stm32_cube_ide/../../../../../third_party/st/devices/stm32f4xx" -I"F:/DS_STM32F429/IAP/CycloneBOOT_IAP_Demo_Open_1_0_1/demo/st/nucleo_f429zi/http_server_iap_demo/stm32_cube_ide/../../../../../third_party/st/drivers/stm32f4xx_hal_driver/inc" -I"F:/DS_STM32F429/IAP/CycloneBOOT_IAP_Demo_Open_1_0_1/demo/st/nucleo_f429zi/http_server_iap_demo/stm32_cube_ide/../../../../../third_party/st/boards/stm32f4xx_nucleo_144" -I"F:/DS_STM32F429/IAP/CycloneBOOT_IAP_Demo_Open_1_0_1/demo/st/nucleo_f429zi/http_server_iap_demo/stm32_cube_ide/../../../../../third_party/freertos/include" -I"F:/DS_STM32F429/IAP/CycloneBOOT_IAP_Demo_Open_1_0_1/demo/st/nucleo_f429zi/http_server_iap_demo/stm32_cube_ide/../../../../../third_party/freertos/portable/gcc/arm_cm4f" -I"F:/DS_STM32F429/IAP/CycloneBOOT_IAP_Demo_Open_1_0_1/demo/st/nucleo_f429zi/http_server_iap_demo/stm32_cube_ide/../../../../../common" -I"F:/DS_STM32F429/IAP/CycloneBOOT_IAP_Demo_Open_1_0_1/demo/st/nucleo_f429zi/http_server_iap_demo/stm32_cube_ide/../../../../../cyclone_tcp" -I"F:/DS_STM32F429/IAP/CycloneBOOT_IAP_Demo_Open_1_0_1/demo/st/nucleo_f429zi/http_server_iap_demo/stm32_cube_ide/../../../../../cyclone_ssl" -I"F:/DS_STM32F429/IAP/CycloneBOOT_IAP_Demo_Open_1_0_1/demo/st/nucleo_f429zi/http_server_iap_demo/stm32_cube_ide/../../../../../cyclone_crypto" -I"F:/DS_STM32F429/IAP/CycloneBOOT_IAP_Demo_Open_1_0_1/demo/st/nucleo_f429zi/http_server_iap_demo/stm32_cube_ide/../../../../../cyclone_boot" -O0 -ffunction-sections -Wall -fstack-usage -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@"  -mfpu=fpv4-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
CycloneBOOT_Sources/iap_auth.o: F:/DS_STM32F429/IAP/CycloneBOOT_IAP_Demo_Open_1_0_1/cyclone_boot/iap/iap_auth.c CycloneBOOT_Sources/subdir.mk
	arm-none-eabi-gcc "$<" -mcpu=cortex-m4 -std=gnu11 -g3 -DSTM32F429xx -DUSE_HAL_DRIVER -DUSE_STM32F4XX_NUCLEO_144 -DIAP_SCENARIO_1 -D_WINSOCK_H -c -I"F:/DS_STM32F429/IAP/CycloneBOOT_IAP_Demo_Open_1_0_1/demo/st/nucleo_f429zi/http_server_iap_demo/stm32_cube_ide/../src" -I"F:/DS_STM32F429/IAP/CycloneBOOT_IAP_Demo_Open_1_0_1/demo/st/nucleo_f429zi/http_server_iap_demo/stm32_cube_ide/../../../../../third_party/cmsis/include" -I"F:/DS_STM32F429/IAP/CycloneBOOT_IAP_Demo_Open_1_0_1/demo/st/nucleo_f429zi/http_server_iap_demo/stm32_cube_ide/../../../../../third_party/st/devices/stm32f4xx" -I"F:/DS_STM32F429/IAP/CycloneBOOT_IAP_Demo_Open_1_0_1/demo/st/nucleo_f429zi/http_server_iap_demo/stm32_cube_ide/../../../../../third_party/st/drivers/stm32f4xx_hal_driver/inc" -I"F:/DS_STM32F429/IAP/CycloneBOOT_IAP_Demo_Open_1_0_1/demo/st/nucleo_f429zi/http_server_iap_demo/stm32_cube_ide/../../../../../third_party/st/boards/stm32f4xx_nucleo_144" -I"F:/DS_STM32F429/IAP/CycloneBOOT_IAP_Demo_Open_1_0_1/demo/st/nucleo_f429zi/http_server_iap_demo/stm32_cube_ide/../../../../../third_party/freertos/include" -I"F:/DS_STM32F429/IAP/CycloneBOOT_IAP_Demo_Open_1_0_1/demo/st/nucleo_f429zi/http_server_iap_demo/stm32_cube_ide/../../../../../third_party/freertos/portable/gcc/arm_cm4f" -I"F:/DS_STM32F429/IAP/CycloneBOOT_IAP_Demo_Open_1_0_1/demo/st/nucleo_f429zi/http_server_iap_demo/stm32_cube_ide/../../../../../common" -I"F:/DS_STM32F429/IAP/CycloneBOOT_IAP_Demo_Open_1_0_1/demo/st/nucleo_f429zi/http_server_iap_demo/stm32_cube_ide/../../../../../cyclone_tcp" -I"F:/DS_STM32F429/IAP/CycloneBOOT_IAP_Demo_Open_1_0_1/demo/st/nucleo_f429zi/http_server_iap_demo/stm32_cube_ide/../../../../../cyclone_ssl" -I"F:/DS_STM32F429/IAP/CycloneBOOT_IAP_Demo_Open_1_0_1/demo/st/nucleo_f429zi/http_server_iap_demo/stm32_cube_ide/../../../../../cyclone_crypto" -I"F:/DS_STM32F429/IAP/CycloneBOOT_IAP_Demo_Open_1_0_1/demo/st/nucleo_f429zi/http_server_iap_demo/stm32_cube_ide/../../../../../cyclone_boot" -O0 -ffunction-sections -Wall -fstack-usage -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@"  -mfpu=fpv4-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
CycloneBOOT_Sources/iap_check.o: F:/DS_STM32F429/IAP/CycloneBOOT_IAP_Demo_Open_1_0_1/cyclone_boot/iap/iap_check.c CycloneBOOT_Sources/subdir.mk
	arm-none-eabi-gcc "$<" -mcpu=cortex-m4 -std=gnu11 -g3 -DSTM32F429xx -DUSE_HAL_DRIVER -DUSE_STM32F4XX_NUCLEO_144 -DIAP_SCENARIO_1 -D_WINSOCK_H -c -I"F:/DS_STM32F429/IAP/CycloneBOOT_IAP_Demo_Open_1_0_1/demo/st/nucleo_f429zi/http_server_iap_demo/stm32_cube_ide/../src" -I"F:/DS_STM32F429/IAP/CycloneBOOT_IAP_Demo_Open_1_0_1/demo/st/nucleo_f429zi/http_server_iap_demo/stm32_cube_ide/../../../../../third_party/cmsis/include" -I"F:/DS_STM32F429/IAP/CycloneBOOT_IAP_Demo_Open_1_0_1/demo/st/nucleo_f429zi/http_server_iap_demo/stm32_cube_ide/../../../../../third_party/st/devices/stm32f4xx" -I"F:/DS_STM32F429/IAP/CycloneBOOT_IAP_Demo_Open_1_0_1/demo/st/nucleo_f429zi/http_server_iap_demo/stm32_cube_ide/../../../../../third_party/st/drivers/stm32f4xx_hal_driver/inc" -I"F:/DS_STM32F429/IAP/CycloneBOOT_IAP_Demo_Open_1_0_1/demo/st/nucleo_f429zi/http_server_iap_demo/stm32_cube_ide/../../../../../third_party/st/boards/stm32f4xx_nucleo_144" -I"F:/DS_STM32F429/IAP/CycloneBOOT_IAP_Demo_Open_1_0_1/demo/st/nucleo_f429zi/http_server_iap_demo/stm32_cube_ide/../../../../../third_party/freertos/include" -I"F:/DS_STM32F429/IAP/CycloneBOOT_IAP_Demo_Open_1_0_1/demo/st/nucleo_f429zi/http_server_iap_demo/stm32_cube_ide/../../../../../third_party/freertos/portable/gcc/arm_cm4f" -I"F:/DS_STM32F429/IAP/CycloneBOOT_IAP_Demo_Open_1_0_1/demo/st/nucleo_f429zi/http_server_iap_demo/stm32_cube_ide/../../../../../common" -I"F:/DS_STM32F429/IAP/CycloneBOOT_IAP_Demo_Open_1_0_1/demo/st/nucleo_f429zi/http_server_iap_demo/stm32_cube_ide/../../../../../cyclone_tcp" -I"F:/DS_STM32F429/IAP/CycloneBOOT_IAP_Demo_Open_1_0_1/demo/st/nucleo_f429zi/http_server_iap_demo/stm32_cube_ide/../../../../../cyclone_ssl" -I"F:/DS_STM32F429/IAP/CycloneBOOT_IAP_Demo_Open_1_0_1/demo/st/nucleo_f429zi/http_server_iap_demo/stm32_cube_ide/../../../../../cyclone_crypto" -I"F:/DS_STM32F429/IAP/CycloneBOOT_IAP_Demo_Open_1_0_1/demo/st/nucleo_f429zi/http_server_iap_demo/stm32_cube_ide/../../../../../cyclone_boot" -O0 -ffunction-sections -Wall -fstack-usage -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@"  -mfpu=fpv4-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
CycloneBOOT_Sources/iap_cipher.o: F:/DS_STM32F429/IAP/CycloneBOOT_IAP_Demo_Open_1_0_1/cyclone_boot/iap/iap_cipher.c CycloneBOOT_Sources/subdir.mk
	arm-none-eabi-gcc "$<" -mcpu=cortex-m4 -std=gnu11 -g3 -DSTM32F429xx -DUSE_HAL_DRIVER -DUSE_STM32F4XX_NUCLEO_144 -DIAP_SCENARIO_1 -D_WINSOCK_H -c -I"F:/DS_STM32F429/IAP/CycloneBOOT_IAP_Demo_Open_1_0_1/demo/st/nucleo_f429zi/http_server_iap_demo/stm32_cube_ide/../src" -I"F:/DS_STM32F429/IAP/CycloneBOOT_IAP_Demo_Open_1_0_1/demo/st/nucleo_f429zi/http_server_iap_demo/stm32_cube_ide/../../../../../third_party/cmsis/include" -I"F:/DS_STM32F429/IAP/CycloneBOOT_IAP_Demo_Open_1_0_1/demo/st/nucleo_f429zi/http_server_iap_demo/stm32_cube_ide/../../../../../third_party/st/devices/stm32f4xx" -I"F:/DS_STM32F429/IAP/CycloneBOOT_IAP_Demo_Open_1_0_1/demo/st/nucleo_f429zi/http_server_iap_demo/stm32_cube_ide/../../../../../third_party/st/drivers/stm32f4xx_hal_driver/inc" -I"F:/DS_STM32F429/IAP/CycloneBOOT_IAP_Demo_Open_1_0_1/demo/st/nucleo_f429zi/http_server_iap_demo/stm32_cube_ide/../../../../../third_party/st/boards/stm32f4xx_nucleo_144" -I"F:/DS_STM32F429/IAP/CycloneBOOT_IAP_Demo_Open_1_0_1/demo/st/nucleo_f429zi/http_server_iap_demo/stm32_cube_ide/../../../../../third_party/freertos/include" -I"F:/DS_STM32F429/IAP/CycloneBOOT_IAP_Demo_Open_1_0_1/demo/st/nucleo_f429zi/http_server_iap_demo/stm32_cube_ide/../../../../../third_party/freertos/portable/gcc/arm_cm4f" -I"F:/DS_STM32F429/IAP/CycloneBOOT_IAP_Demo_Open_1_0_1/demo/st/nucleo_f429zi/http_server_iap_demo/stm32_cube_ide/../../../../../common" -I"F:/DS_STM32F429/IAP/CycloneBOOT_IAP_Demo_Open_1_0_1/demo/st/nucleo_f429zi/http_server_iap_demo/stm32_cube_ide/../../../../../cyclone_tcp" -I"F:/DS_STM32F429/IAP/CycloneBOOT_IAP_Demo_Open_1_0_1/demo/st/nucleo_f429zi/http_server_iap_demo/stm32_cube_ide/../../../../../cyclone_ssl" -I"F:/DS_STM32F429/IAP/CycloneBOOT_IAP_Demo_Open_1_0_1/demo/st/nucleo_f429zi/http_server_iap_demo/stm32_cube_ide/../../../../../cyclone_crypto" -I"F:/DS_STM32F429/IAP/CycloneBOOT_IAP_Demo_Open_1_0_1/demo/st/nucleo_f429zi/http_server_iap_demo/stm32_cube_ide/../../../../../cyclone_boot" -O0 -ffunction-sections -Wall -fstack-usage -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@"  -mfpu=fpv4-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
CycloneBOOT_Sources/iap_sign.o: F:/DS_STM32F429/IAP/CycloneBOOT_IAP_Demo_Open_1_0_1/cyclone_boot/iap/iap_sign.c CycloneBOOT_Sources/subdir.mk
	arm-none-eabi-gcc "$<" -mcpu=cortex-m4 -std=gnu11 -g3 -DSTM32F429xx -DUSE_HAL_DRIVER -DUSE_STM32F4XX_NUCLEO_144 -DIAP_SCENARIO_1 -D_WINSOCK_H -c -I"F:/DS_STM32F429/IAP/CycloneBOOT_IAP_Demo_Open_1_0_1/demo/st/nucleo_f429zi/http_server_iap_demo/stm32_cube_ide/../src" -I"F:/DS_STM32F429/IAP/CycloneBOOT_IAP_Demo_Open_1_0_1/demo/st/nucleo_f429zi/http_server_iap_demo/stm32_cube_ide/../../../../../third_party/cmsis/include" -I"F:/DS_STM32F429/IAP/CycloneBOOT_IAP_Demo_Open_1_0_1/demo/st/nucleo_f429zi/http_server_iap_demo/stm32_cube_ide/../../../../../third_party/st/devices/stm32f4xx" -I"F:/DS_STM32F429/IAP/CycloneBOOT_IAP_Demo_Open_1_0_1/demo/st/nucleo_f429zi/http_server_iap_demo/stm32_cube_ide/../../../../../third_party/st/drivers/stm32f4xx_hal_driver/inc" -I"F:/DS_STM32F429/IAP/CycloneBOOT_IAP_Demo_Open_1_0_1/demo/st/nucleo_f429zi/http_server_iap_demo/stm32_cube_ide/../../../../../third_party/st/boards/stm32f4xx_nucleo_144" -I"F:/DS_STM32F429/IAP/CycloneBOOT_IAP_Demo_Open_1_0_1/demo/st/nucleo_f429zi/http_server_iap_demo/stm32_cube_ide/../../../../../third_party/freertos/include" -I"F:/DS_STM32F429/IAP/CycloneBOOT_IAP_Demo_Open_1_0_1/demo/st/nucleo_f429zi/http_server_iap_demo/stm32_cube_ide/../../../../../third_party/freertos/portable/gcc/arm_cm4f" -I"F:/DS_STM32F429/IAP/CycloneBOOT_IAP_Demo_Open_1_0_1/demo/st/nucleo_f429zi/http_server_iap_demo/stm32_cube_ide/../../../../../common" -I"F:/DS_STM32F429/IAP/CycloneBOOT_IAP_Demo_Open_1_0_1/demo/st/nucleo_f429zi/http_server_iap_demo/stm32_cube_ide/../../../../../cyclone_tcp" -I"F:/DS_STM32F429/IAP/CycloneBOOT_IAP_Demo_Open_1_0_1/demo/st/nucleo_f429zi/http_server_iap_demo/stm32_cube_ide/../../../../../cyclone_ssl" -I"F:/DS_STM32F429/IAP/CycloneBOOT_IAP_Demo_Open_1_0_1/demo/st/nucleo_f429zi/http_server_iap_demo/stm32_cube_ide/../../../../../cyclone_crypto" -I"F:/DS_STM32F429/IAP/CycloneBOOT_IAP_Demo_Open_1_0_1/demo/st/nucleo_f429zi/http_server_iap_demo/stm32_cube_ide/../../../../../cyclone_boot" -O0 -ffunction-sections -Wall -fstack-usage -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@"  -mfpu=fpv4-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
CycloneBOOT_Sources/stm32f4xx_flash_driver.o: F:/DS_STM32F429/IAP/CycloneBOOT_IAP_Demo_Open_1_0_1/cyclone_boot/iap/drivers/stm32f4xx_flash_driver.c CycloneBOOT_Sources/subdir.mk
	arm-none-eabi-gcc "$<" -mcpu=cortex-m4 -std=gnu11 -g3 -DSTM32F429xx -DUSE_HAL_DRIVER -DUSE_STM32F4XX_NUCLEO_144 -DIAP_SCENARIO_1 -D_WINSOCK_H -c -I"F:/DS_STM32F429/IAP/CycloneBOOT_IAP_Demo_Open_1_0_1/demo/st/nucleo_f429zi/http_server_iap_demo/stm32_cube_ide/../src" -I"F:/DS_STM32F429/IAP/CycloneBOOT_IAP_Demo_Open_1_0_1/demo/st/nucleo_f429zi/http_server_iap_demo/stm32_cube_ide/../../../../../third_party/cmsis/include" -I"F:/DS_STM32F429/IAP/CycloneBOOT_IAP_Demo_Open_1_0_1/demo/st/nucleo_f429zi/http_server_iap_demo/stm32_cube_ide/../../../../../third_party/st/devices/stm32f4xx" -I"F:/DS_STM32F429/IAP/CycloneBOOT_IAP_Demo_Open_1_0_1/demo/st/nucleo_f429zi/http_server_iap_demo/stm32_cube_ide/../../../../../third_party/st/drivers/stm32f4xx_hal_driver/inc" -I"F:/DS_STM32F429/IAP/CycloneBOOT_IAP_Demo_Open_1_0_1/demo/st/nucleo_f429zi/http_server_iap_demo/stm32_cube_ide/../../../../../third_party/st/boards/stm32f4xx_nucleo_144" -I"F:/DS_STM32F429/IAP/CycloneBOOT_IAP_Demo_Open_1_0_1/demo/st/nucleo_f429zi/http_server_iap_demo/stm32_cube_ide/../../../../../third_party/freertos/include" -I"F:/DS_STM32F429/IAP/CycloneBOOT_IAP_Demo_Open_1_0_1/demo/st/nucleo_f429zi/http_server_iap_demo/stm32_cube_ide/../../../../../third_party/freertos/portable/gcc/arm_cm4f" -I"F:/DS_STM32F429/IAP/CycloneBOOT_IAP_Demo_Open_1_0_1/demo/st/nucleo_f429zi/http_server_iap_demo/stm32_cube_ide/../../../../../common" -I"F:/DS_STM32F429/IAP/CycloneBOOT_IAP_Demo_Open_1_0_1/demo/st/nucleo_f429zi/http_server_iap_demo/stm32_cube_ide/../../../../../cyclone_tcp" -I"F:/DS_STM32F429/IAP/CycloneBOOT_IAP_Demo_Open_1_0_1/demo/st/nucleo_f429zi/http_server_iap_demo/stm32_cube_ide/../../../../../cyclone_ssl" -I"F:/DS_STM32F429/IAP/CycloneBOOT_IAP_Demo_Open_1_0_1/demo/st/nucleo_f429zi/http_server_iap_demo/stm32_cube_ide/../../../../../cyclone_crypto" -I"F:/DS_STM32F429/IAP/CycloneBOOT_IAP_Demo_Open_1_0_1/demo/st/nucleo_f429zi/http_server_iap_demo/stm32_cube_ide/../../../../../cyclone_boot" -O0 -ffunction-sections -Wall -fstack-usage -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@"  -mfpu=fpv4-sp-d16 -mfloat-abi=hard -mthumb -o "$@"

